### ISSUE TITLE
What is the baseurl and how can we init the order using the api? 

### ISSUE THREAD

**Issue by zuhairabbs** [Wajahat-Jawaid/SafepayAndroidIntegration#1]
I tried hitting https://sandbox.api.getsafepay.com/components/order/v1/init but instead of a response object i got a html page

**Comment by Wajahat-Jawaid** [comment]
Hi @zuhairabbs can you please post parameters that you are sending along?

**Comment by zuhairabbs** [comment]
hi @Wajahat-Jawaid i am not posting any parameters along, Can you share what exactly needs to be sent?

**Comment by Wajahat-Jawaid** [comment]
You need to pass instance of #SafepayRequestModel class to /v1/init API.

https://github.com/Wajahat-Jawaid/SafepayAndroidIntegration/blob/master/app/src/main/java/com/wajahat/safepayandroidintegration/model/SafepayRequestModel.java

**Comment by zuhairabbs** [comment]
what exactly is the /v1/init api, What is the base url?

**Comment by Wajahat-Jawaid** [comment]
https://sandbox.api.getsafepay.com/components/order/v1/init

**Comment by zuhairabbs** [comment]
these are my params:
curl --location --request POST 'https://sandbox.api.getsafepay.com/components/order/v1/init' \
--header 'Content-Type: application/json' \
--data-raw '{
  "currency": "USD",
  "amount": 12,
  "environment": "sandbox",
  "client": "a52a97134f4aedaebc72a6888fa3586b60b091caf9d57dad66e2cd7ff858d8ef"
}'

this is what i am trying  and getting this html page as response
<!doctype html>
<html lang="en">

<head>
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-113510024-2"></script>
	<script>
		function gtag(){dataLayer.push(arguments)}window.dataLayer=window.dataLayer||[],gtag("js",new Date),gtag("config","UA-113510024-2")
	</script>
	<meta charset="utf-8" />
	<link rel="shortcut icon" href="https://sandbox.api.getsafepay.com/components/favicon.ico" />
	<meta name="viewport" content="width=device-width,initial-scale=1" />
	<meta name="theme-color" content="#000000" />
	<meta name="description" content="Safepay Checkout - Secure, Reliable Payments" />
	<link rel="apple-touch-icon" href="logo192.png" />
	<link rel="manifest" href="https://sandbox.api.getsafepay.com/components/manifest.json" />
	<script src="https://storage.googleapis.com/safepayobjects/api/safepay-checkout.min.js"></script>
	<title>Safepay Checkout</title>
	<link href="https://sandbox.api.getsafepay.com/components/static/css/main.95e3b4f1.chunk.css" rel="stylesheet">
</head>

<body><noscript>You need to enable JavaScript to run this app.</noscript>
	<div id="root"></div>
	<script type="text/javascript">
		var SESSION_ID="",COUNTRY="",ENVIRONMENT="";window.__SERVER_VARS__={},window.__SERVER_VARS__.attributes={sessionId:SESSION_ID,country:COUNTRY,environment:ENVIRONMENT}
	</script>
	<p style="margin:0;background:url(https://h.online-metrix.net/fp/clear.png?org_id=k8vif92e&session_id=hbl_ift&m=1)">
	</p><img src="https://h.online-metrix.net/fp/clear.png?org_id=k8vif92e&session_id=hbl_ift&m=2" alt=""/>
	<object type="application/x-shockwave-flash" data="https://h.online-metrix.net/fp/fp.swf?org_id=k8vif92e&session_id=hbl_ift" width="1" height="1" id="thm_fp"><param name="movie" value="https://h.online-metrix.net/fp/fp.swf?org_id=k8vif92e&session_id=hbl_ift"/><div></div></object>
	<script type="text/javascript" src="https://h.online-metrix.net/fp/tags.js?org_id=k8vif92e&session_id=hbl_ift">
	</script><noscript><iframe style="width:100px;height:100px;border:0;position:absolute;top:-5000px"
			src="https://h.online-metrix.net/fp/tags?org_id=k8vif92e&session_id=hbl_ift"></iframe></noscript>
	<script>
		!function(l){function e(e){for(var t,n,r=e[0],o=e[1],u=e[2],a=0,p=[];a<r.length;a++)n=r[a],Object.prototype.hasOwnProperty.call(f,n)&&f[n]&&p.push(f[n][0]),f[n]=0;for(t in o)Object.prototype.hasOwnProperty.call(o,t)&&(l[t]=o[t]);for(s&&s(e);p.length;)p.shift()();return i.push.apply(i,u||[]),c()}function c(){for(var e,t=0;t<i.length;t++){for(var n=i[t],r=!0,o=1;o<n.length;o++){var u=n[o];0!==f[u]&&(r=!1)}r&&(i.splice(t--,1),e=a(a.s=n[0]))}return e}var n={},f={1:0},i=[];function a(e){if(n[e])return n[e].exports;var t=n[e]={i:e,l:!1,exports:{}};return l[e].call(t.exports,t,t.exports,a),t.l=!0,t.exports}a.m=l,a.c=n,a.d=function(e,t,n){a.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:n})},a.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},a.t=function(t,e){if(1&e&&(t=a(t)),8&e)return t;if(4&e&&"object"==typeof t&&t&&t.__esModule)return t;var n=Object.create(null);if(a.r(n),Object.defineProperty(n,"default",{enumerable:!0,value:t}),2&e&&"string"!=typeof t)for(var r in t)a.d(n,r,function(e){return t[e]}.bind(null,r));return n},a.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return a.d(t,"a",t),t},a.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},a.p="https://sandbox.api.getsafepay.com/components/";var t=window["webpackJsonptrojan-components"]=window["webpackJsonptrojan-components"]||[],r=t.push.bind(t);t.push=e,t=t.slice();for(var o=0;o<t.length;o++)e(t[o]);var s=r;c()}([])
	</script>
	<script src="https://sandbox.api.getsafepay.com/components/static/js/2.34c92b0c.chunk.js"></script>
	<script src="https://sandbox.api.getsafepay.com/components/static/js/main.cd77776c.chunk.js"></script>
</body>

</html>

**Comment by zuhairabbs** [comment]
So i have got the solution to the question i was asking, The issue is in the base url, The correct base url that should be used is 
https://sandbox.api.getsafepay.com/order/v1/init
instead of 
https://sandbox.api.getsafepay.com/components/order/v1/init
posting this as it might help others save time thanks for the support wajahat

**Comment by Wajahat-Jawaid** [comment]
Great @zuhairabbs !
